### ISSUE TITLE
NullReferenceException in user details

### ISSUE THREAD

**Issue by jwillmer** [StarcounterPrefabs/UserAdmin#13] opened 2016-01-18 16:31 UTC
If I display the list of all users and click on a user (to open the details) I get a null reference exception. (I have stoped the launcher and used the app as stand alone.)

Log:
```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Starcounter.Json.Refresh(Template property) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Class Json\Json.cs:Zeile 300.
   bei Starcounter.Json.InitBoundArrays(TValue template) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:Zeile 146.
   bei Starcounter.Json.InternalSetData(Object data, TValue template, Boolean readOperation) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:Zeile 98.
   bei Starcounter.Internal.TransactionManager.Scope[T1,T2](TransactionHandle handle, Action`2 action, T1 arg1, T2 arg2) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\TransactionManager.cs:Zeile 471.
   bei Starcounter.Advanced.XSON.JsonExtension.Scope[T1,T2](Json json, Action`2 action, T1 arg1, T2 arg2) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Class Json\JsonExtension.cs:Zeile 77.
   bei Starcounter.Json.set_Data(Object value) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.XSON\Class Json\Json.Object.Data.cs:Zeile 38.
   bei UserAdmin.SystemUsersHandlers.<>c__DisplayClassf.<Register>b__a(String uri, SystemUser personUser) in c:\github\StarcounterSamples\UserAdmin\src\UserAdmin\Api\SystemUsersHandlers.cs:Zeile 81.
   bei Starcounter.Db.Scope[T1,T2,TResult](Func`3 func, T1 arg1, T2 arg2, Boolean isReadOnly) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Db.cs:Zeile 334.
   bei UserAdmin.SystemUsersHandlers.<>c__DisplayClassf.<Register>b__9(String userid, Request request) in c:\github\StarcounterSamples\UserAdmin\src\UserAdmin\Api\SystemUsersHandlers.cs:Zeile 80.
   bei lambda_method(Closure , Request , IntPtr , IntPtr )
   bei Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Rest\UriHandlersManager.cs:Zeile 266.
   bei Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:Zeile 98.
   bei Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:Zeile 1119.
   bei Starcounter.Self.DoSelfNodeCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Internal\Rest\Self.cs:Zeile 392.
   bei Starcounter.Self.GET(UInt16 port, String uri, Dictionary`2 headersDictionary, HandlerOptions ho) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Internal\Rest\Self.cs:Zeile 133.
   bei Starcounter.UriMapping.<>c__DisplayClass1a.<CallAllHandlersForClass>b__19(HandlerInfoForUriMapping x) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:Zeile 801.
   bei Starcounter.UriMapping.CallAllHandlersForClass(List`1 resps, MappingClassInfo type, String stringParam, List`1 alreadyCalledHandlers) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:Zeile 818.
   bei Starcounter.UriMapping.CallAllHandlersInTypeHierarchy(Request req, String className, String paramStr) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:Zeile 705.
   bei Starcounter.UriMapping.ClassHierarchyCallProxy(Request req, String className, String paramStr) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:Zeile 960.
   bei lambda_method(Closure , Request , IntPtr , IntPtr )
   bei Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Rest\UriHandlersManager.cs:Zeile 200.
   bei Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:Zeile 98.
   bei Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:Zeile 1119.
   bei Starcounter.Self.DoSelfNodeCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Internal\Rest\Self.cs:Zeile 392.
   bei Starcounter.Self.GET(UInt16 port, String uri, Dictionary`2 headersDictionary, HandlerOptions ho) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Internal\Rest\Self.cs:Zeile 133.
   bei Starcounter.UriMapping.<>c__DisplayClass17.<OntologyMap>b__16(Request req, String appObjectId) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Apps\OntologyAndOrdinaryMapping.cs:Zeile 572.
   bei lambda_method(Closure , Request , IntPtr , IntPtr )
   bei Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Rest\UriHandlersManager.cs:Zeile 200.
   bei Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:Zeile 98.
   bei Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:Zeile 461.
HResult=-2147467261
```

I am running the current stable Starcounter Version: 2.1.177

**Comment by per-samuelsson** [comment] 2016-01-18 16:47
I talked to @jwillmer and one suspicion he had was that his Starcounter version could be older than what the newest UserAdmin app is designed for. Could that be so?

Any other ideas, @warpech, @miyconst?

**Comment by warpech** [comment] 2016-01-19 15:27
Steps to reproduce on a clean db:

1. Start Launcher, Sign In, User Admin
2. Go to this url http://localhost:8080/UserAdmin/admin/users
3. Click on "admin" link on users list

It is reproducible with: 
- Starcounter 2.1.177
- User Admin 2.0.0-pre8 (as well as master)
- SignIn 3.1.11 (as well as master)
- Launcher 3.0.13 (as well as master)

It is not reproducible with current nightly (Starcounter 2.1.1048)

**Comment by warpech** [comment] 2016-01-19 15:27
I've spent 1 hour investigating this but didn't find a solution. 

To fix this for @jwillmer we need to either:

1. dig deeper (@andwah would need to take a look)
2. release a new stable and ask @jwillmer to upgrade

@dan31 what do you say?

**Comment by per-samuelsson** [comment] 2016-01-19 15:35
> @dan31 what do you say?

Let's see what @jwillmer says first. I'm about to have a talk with him anyway, about...

> release a new stable and ask @jwillmer to upgrade

just that! Because we are in the starting phase starting to test some new functionality, and this new functionality is only in our very latest bits, so we are very close to reach a point where we need @jwillmer to upgrade to that, and that's what him and me are about to discuss.

Give me like until tomorrow or so, and I'll come back with some new info. Thanks for all the help so far @warpech!

**Comment by jwillmer** [comment] 2016-01-19 15:43
I have no problems to upgrade but I think that it is important that your published apps are compatible with at least the latest stable release. And that they will be tested against it before they get published in the store ;-)

**Comment by warpech** [comment] 2016-01-19 15:51
> I have no problems to upgrade but I think that it is important that your published apps are compatible with at least the latest stable release. And that they will be tested against it before they get published in the store ;-)

Totally agree! We will use more automated tests to fix that.

**Comment by per-samuelsson** [comment] 2016-01-19 15:51
>  [...] I think that it is important that your published apps are compatible with at least the latest stable release.

Well, totally agree. And we must definitely improve in general on that. But our first prio would o/c be to get you through this, and that's what I wanted to talk to you about.

**Comment by per-samuelsson** [comment] 2016-01-19 15:52
(@warpech beat me by like 5 seconds :bug:)

**Comment by warpech** [comment] 2016-08-16 15:14
Closing as not reproducible anymore (see https://github.com/StarcounterPrefabs/UserAdmin/issues/13#issuecomment-172888014)

**Closed by warpech** 2016-08-16 15:14 UTC
